version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes: 
      - ../pgdb:/var/lib/postgresql/data
    env_file:
      ../.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
