# Generated by Django 5.2 on 2025-05-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0004_rulecategory_delete_definition_rule_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulecategory',
            options={'verbose_name_plural': 'Rule Categories'},
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='grammars.rulecategory'),
        ),
    ]
