# Generated by Django 5.2 on 2025-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('comment', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=9)),
                ('accept_policy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
