# Generated by Django 5.2 on 2025-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
