# Generated by Django 5.2 on 2025-05-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0005_alter_rulecategory_options_rulecategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulecategory',
            name='parent',
        ),
        migrations.CreateModel(
            name='RuleSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sub_category', to='grammars.rulecategory')),
            ],
            options={
                'verbose_name_plural': 'Rule Categories',
            },
        ),
    ]
