# Generated by Django 5.2 on 2025-05-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0006_remove_rulecategory_parent_rulesubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='category',
        ),
        migrations.AddField(
            model_name='rule',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='grammars.rulesubcategory'),
            preserve_default=False,
        ),
    ]
