# Generated by Django 5.2 on 2025-05-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0007_remove_rule_category_rule_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulesubcategory',
            options={'verbose_name_plural': 'Rule SubCategories'},
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
