# Generated by Django 5.2 on 2025-05-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0008_alter_rulesubcategory_options_delete_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesubcategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grammars.rulecategory'),
        ),
    ]
