# Generated by Django 5.2 on 2025-07-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
