# Generated by Django 5.1.7 on 2025-07-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike'), ('unlike_comment', 'Unlike Comment'), ('post_create', 'Post Create'), ('reply', 'Reply'), ('comment_like', 'Like comment'), ('commented_comment', 'Commented to comment')], max_length=50),
        ),
    ]
