# Generated by Django 5.1.7 on 2025-07-19 05:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', validators=[core.validators.validate_file_size]),
        ),
    ]
