# Generated by Django 5.1.7 on 2025-06-18 11:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_check_up_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_up',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[core.models.validate_file_size, core.models.validate_file_type]),
        ),
    ]
